name: douyin
on:
  workflow_dispatch:
  schedule:
    # 每天凌晨执行，UTC 时间，这里是凌晨12点
    - cron: '0 0 * * *'

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Install yt-dlp
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install yt-dlp
          yt-dlp --version         

      - name: douyin
        run: java -jar test/test-plugin-0.3-jar-with-dependencies.jar https://v.douyin.com/UdEX4jw/