name: ntdm

on:
  workflow_dispatch:
  schedule:
    # 每天凌晨执行，UTC 时间，这里是凌晨12点
    - cron: '0 0 * * *'

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg          

      - name: ntdm
        run: java -jar test/read-gitee-pipelines-0.0.1-jar-with-dependencies.jar "${{ secrets.TEST_NTDM_STATUS_URL }}"